version: "3.8"
services:
  app:
    build: .
    container_name: triohotel_app
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "4000"
    volumes:
      - ./logs:/app/logs

  nginx:
    image: nginx:stable-alpine
    container_name: triohotel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro   # cert จาก host
    depends_on:
      - app
